# Generated by Django 5.1 on 2024-08-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='time',
            field=models.IntegerField(default=0, help_text='Total time in seconds for the recipe'),
        ),
    ]
