# Generated by Django 5.1 on 2024-08-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking_app', '0002_recipes_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
